base: ghcr.io/vanilla-os/desktop:main

name: Vanilla Desktop Custom haryp2309

labels:
  maintainer: haryp2309

args:
  DEBIAN_FRONTEND: noninteractive

runs:
- echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends
- /bin/tee --help

modules:

- name: init-setup
  type: shell
  commands:
  - lpkg --unlock
  - apt-get update

- name: install-docker
  type: shell
  commands:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - ls  /etc/apt/sources.list.d
  - echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list 
  - cat /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

- name: install-google-chrome
  type: shell
  commands:
  - curl -fSsL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | tee /usr/share/keyrings/google-chrome.gpg >> /dev/null
  - echo deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main | tee /etc/apt/sources.list.d/google-chrome.list
  - apt-get update
  - apt-get install google-chrome-stable -y

- name: cleanup
  type: shell
  commands:
  - apt-get autoremove -y
  - apt-get clean
  - lpkg --lock
