name: Vib Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_NAME: ghcr.io/haryp2309/custom-vib:main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: vanilla-os/vib-gh-action@v0.3.3-1
      with:
        recipe: 'recipe.yml'

    - name: Build the Docker image
      run: docker image build -f Containerfile --tag ${{ env.IMAGE_NAME }} .

   # Push the image to GHCR (Image Registry)
    - name: Push To GHCR
      run: |
        docker login ghcr.io -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
        docker image push "${{ env.IMAGE_NAME }}"
